apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: qa
  name: res-quota
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: deploy-test
  labels:
    app: deploy-front
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod-label-front
  template:
    metadata:
      labels:
        app: pod-label-front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine