apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv2
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pv-claim2
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      mysql: ready