apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-config
  labels:
    app: pod-label-front
data:
  nginx: |
    server {
        listen       9090;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: vars
  labels:
    app: pod-label-front
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo DB host es $DB_HOST y DB user es $DB_USER > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  labels:
    app: deploy-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label-front
  template:
    metadata:
      labels:
        app: pod-label-front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_user
          volumeMounts:
          - name: script-vol
            mountPath: "/tmp"
          - name: nginx-vol
            mountPath: "/etc/nginx/conf.d"
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items:
            - key: "nginx"
              path: "default.conf"
        - name: script-vol
          configMap:
            name: vars
            items:
            - key: script
              path: script.sh