apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-full-app-frontend
  labels:
    app: k8s-full-app-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-full-app-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: k8s-full-app-frontend
        tier: frontend
    spec:
      containers:
      - name: js-frontend
        image: frontend-k8s-hands-on:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: svc-k8s-full-app-frontend
spec:
  type: NodePort
  selector:
    app: k8s-full-app-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80