apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Primer despliegue"
  name: deploy-test-nodeport
  labels:
    app: app-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-test-nodeport
  labels:
    app: app-backend
spec:
  type: NodePort
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
