apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: dev
  name: mem-cpu-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1000m
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: guayapod
spec:
  containers:
    - name: nginx
      image: nginx:alpine