apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: prod
  name: min-max
spec:
  limits:
  - min:
      memory: 100Mi
      cpu: 100m
    max:
      memory: 1000Mi
      cpu: 1000m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: guayapod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          memory: 50M
          cpu: 50m