apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: deploy-dev
  labels:
    app: deploy-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label-front
  template:
    metadata:
      labels:
        app: pod-label-front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: deploy-prod
  labels:
    app: deploy-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label-front
  template:
    metadata:
      labels:
        app: pod-label-front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine