apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ci
  name: k8s-full-app-backend
  labels:
    app: k8s-full-app-backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-full-app-backend
      tier: backend
  template:
    metadata:
      labels:
        app: k8s-full-app-backend
        tier: backend
    spec:
      containers:
      - name: go-backend
        image: k8s-hands-on:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  namespace: ci
  name: svc-k8s-full-app-backend
spec:
  type: ClusterIP
  selector:
    app: k8s-full-app-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090