apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: cpu-demo2
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      requests:
        cpu: "100000m"
      limits:
        cpu: "100000m"
    args:
      - -cpus
      - "2"